language: perl
perl:
    - "5.8"
    - "5.10"
    - "5.12"
    - "5.14"
    - "5.16"
    - "5.18"
    - "5.20"
sudo: false
notifications:
    on_success: change
    on_failure: always
install:
    - cpanm Dist::Zilla || { cat ~/.cpanm/build.log ; false ; }
    - dzil authordeps --author --missing | cpanm || { cat ~/.cpanm/build.log ; false ; }
    - dzil listdeps --author --missing | cpanm || { cat ~/.cpanm/build.log ; false ; }
script:
    - prove -lv t
    #- dzil test --author --release
    #- dzil xtest
